dist: bionic
language: python
sudo: required
python: "3.7"

install: pip install -r requirements.txt

script: python test.py

deploy:
    provider: heroku
    api_key: $HEROKU_TOKEN
    app: the-price